version: "3"
services:
  backend:
    build:
      context: ./backend # Adjust this to the correct path for your backend Dockerfile
      dockerfile: Dockerfile # If your Dockerfile is named 'Dockerfile' in the 'backend' folder
    ports:
      - "8080:8080"
    networks:
      - app-network

  breeze:
    build:
      context: ./breeze # Adjust this to the correct path for your breeze Dockerfile
      dockerfile: Dockerfile # If your Dockerfile is named 'Dockerfile' in the 'breeze' folder
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Mount your nginx.conf file
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - backend
      - breeze

networks:
  app-network:
    driver: bridge
